# permissions for end users to edit releases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-editor-role
rules:
- apiGroups:
  - core.rswatcher.dev
  resources:
  - releases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.rswatcher.dev
  resources:
  - releases/status
  verbs:
  - get
